import { CarDto } from "../app/data-type/car-data";

/**
 * Global Vehicle Catalog
 * * Data Integrity Note:
 * IDs are assigned as unique numbers (representing Long types from the backend).
 * Images are mapped to the local assets directory.
 */
export const cars: CarDto[] = [
  {
    id: 1001,
    title: 'Porsche Taycan',
    image: 'assets/porsche-taycan-000.png',
    imageAlt: 'Porsche Taycan',
    price: 89900,
    specifications: {
      modelYear: '2024',
      mileage: '5,200 miles',
      engine: 'Dual Electric Motors',
      power: '560 HP',
    },
    description: 'The Porsche Taycan represents the future of luxury electric performance. With lightning-fast acceleration and exceptional build quality.',
    options: [
      { name: 'Premium Paint', price: 2500, selected: false },
      { name: 'Performance Package', price: 5200, selected: false },
      { name: 'Carbon Fiber Interior', price: 3800, selected: false },
      { name: 'Extended Warranty', price: 2100, selected: false },
    ],
    addedToFavorites: false,
  },
  {
    id: 1002,
    title: 'Porsche Panamera',
    image: 'assets/porsche-panamera-000.png',
    imageAlt: 'Porsche Panamera',
    price: 112500,
    specifications: {
      modelYear: '2023',
      mileage: '12,800 miles',
      engine: '4.0L V8 Twin-Turbo',
      power: '630 HP',
    },
    description: 'The Porsche Panamera combines luxury sedan comfort with sports car performance.',
    options: [
      { name: 'Sport Chrono Package', price: 3700, selected: false },
      { name: 'Panoramic Roof', price: 2890, selected: false },
      { name: 'Premium Audio', price: 4200, selected: false },
      { name: 'Adaptive Cruise', price: 1950, selected: false },
    ],
    addedToFavorites: false,
  },
  {
    id: 1003,
    title: 'Mercedes-AMG GT',
    image: 'assets/mercedes-amg-gt-000.png',
    imageAlt: 'Mercedes-AMG GT',
    price: 138200,
    specifications: {
      modelYear: '2024',
      mileage: '3,100 miles',
      engine: '4.0L V8 Biturbo',
      power: '577 HP',
    },
    description: 'The Mercedes-AMG GT embodies racing heritage with aggressive styling and powerful performance.',
    options: [
      { name: 'AMG Track Package', price: 6500, selected: false },
      { name: 'Carbon Fiber Trim', price: 3200, selected: false },
      { name: 'Ceramic Brakes', price: 8900, selected: false },
      { name: 'Exclusive Interior', price: 4800, selected: false },
    ],
    addedToFavorites: false,
  },
  {
    id: 1004,
    title: 'BMW M4 Competition',
    image: 'assets/bmw-m4-competition-000.png',
    imageAlt: 'BMW M4 Competition',
    price: 95400,
    specifications: {
      modelYear: '2023',
      mileage: '8,750 miles',
      engine: '3.0L I6 Twin-Turbo',
      power: '503 HP',
    },
    description: 'Track-focused precision meets peak performance engineering.',
    options: [
      { name: 'M Performance Parts', price: 4500, selected: false },
      { name: 'Carbon Fiber Roof', price: 3600, selected: false },
      { name: 'Harman Kardon Audio', price: 2300, selected: false },
      { name: 'Driver Assistance', price: 1800, selected: false },
    ],
    addedToFavorites: false,
  },
  {
    id: 1005,
    title: 'Audi RS6 Avant',
    image: 'assets/audi-rs6-avant-000.png',
    imageAlt: 'Audi RS6 Avant',
    price: 127800,
    specifications: {
      modelYear: '2024',
      mileage: '6,400 miles',
      engine: '4.0L V8 TFSI',
      power: '591 HP',
    },
    description: 'Supercar acceleration with the versatility of a luxury estate.',
    options: [
      { name: 'RS Sport Package', price: 5800, selected: false },
      { name: 'Matrix LED Lights', price: 2400, selected: false },
      { name: 'Bang & Olufsen Audio', price: 3900, selected: false },
      { name: 'Dynamic Package', price: 4200, selected: false },
    ],
    addedToFavorites: false,
  },
  {
    id: 1006,
    title: 'Ferrari 488 GTB',
    image: 'assets/ferrari-488-gtb-000.png',
    imageAlt: 'Ferrari 488 GTB',
    price: 245900,
    specifications: {
      modelYear: '2022',
      mileage: '4,200 miles',
      engine: '3.9L V8 Twin-Turbo',
      power: '661 HP',
    },
    description: 'A masterpiece of Italian engineering and stunning aesthetics.',
    options: [
      { name: 'Racing Package', price: 12500, selected: false },
      { name: 'Carbon Fiber Aero', price: 8900, selected: false },
      { name: 'Premium Interior', price: 15200, selected: false },
      { name: 'Telemetry System', price: 6800, selected: false },
    ],
    addedToFavorites: false,
  },
  {
    id: 1007,
    title: 'Porsche 911 GT3 RS',
    image: 'assets/porsche-911-gt3-rs-000.png',
    imageAlt: 'Porsche 911 GT3 RS',
    price: 315000,
    specifications: {
      modelYear: '2024',
      mileage: '1,200 miles',
      engine: '4.0L Flat-6 NA',
      power: '518 HP',
    },
    description: 'Active aerodynamics and high-revving naturally aspirated power.',
    options: [
      { name: 'Weissach Package', price: 33500, selected: false },
      { name: 'Magnesium Wheels', price: 12000, selected: false },
      { name: 'PCCB Ceramic Brakes', price: 9800, selected: false },
      { name: 'Front Axle Lift', price: 3600, selected: false },
    ],
    addedToFavorites: false,
  },
  {
    id: 1008,
    title: 'McLaren 765LT',
    image: 'assets/mclaren-765lt-000.png',
    imageAlt: 'McLaren 765LT',
    price: 485000,
    specifications: {
      modelYear: '2022',
      mileage: '2,100 miles',
      engine: '4.0L V8 Twin-Turbo',
      power: '755 HP',
    },
    description: 'Lighter, faster, and circuit-focused "Long Tail" model.',
    options: [
      { name: 'MSO Clubsport Pack', price: 18000, selected: false },
      { name: 'Roof Scoop', price: 35000, selected: false },
      { name: 'Carbon Fibre Fenders', price: 8500, selected: false },
      { name: 'Titanium Exhaust', price: 6200, selected: false },
    ],
    addedToFavorites: false,
  },
  {
    id: 1009,
    title: 'Lamborghini Aventador SVJ',
    image: 'assets/lamborghini-aventador-svj-000.png',
    imageAlt: 'Lamborghini Aventador SVJ',
    price: 650000,
    specifications: {
      modelYear: '2021',
      mileage: '3,400 miles',
      engine: '6.5L V12',
      power: '759 HP',
    },
    description: 'The final celebration of the naturally aspirated V12 era.',
    options: [
      { name: 'Viola Pasifae Paint', price: 14000, selected: false },
      { name: 'Carbon Skin Interior', price: 5600, selected: false },
      { name: 'Telemetry System', price: 4200, selected: false },
      { name: 'Style Package', price: 8500, selected: false },
    ],
    addedToFavorites: false,
  },
  {
    id: 1010,
    title: 'Bugatti Chiron Pur Sport',
    image: 'assets/bugatti-chiron-pur-sport-000.png',
    imageAlt: 'Bugatti Chiron Pur Sport',
    price: 3800000,
    specifications: {
      modelYear: '2022',
      mileage: '450 miles',
      engine: '8.0L W16 Quad-Turbo',
      power: '1479 HP',
    },
    description: 'Focused on lateral dynamics and high-revving agility.',
    options: [
      { name: 'Sky View Roof', price: 62000, selected: false },
      { name: 'Carbon Aero Blades', price: 15000, selected: false },
      { name: 'Custom Stitching', price: 8500, selected: false },
      { name: 'Magnesium Wheels', price: 25000, selected: false },
    ],
    addedToFavorites: false,
  },
  {
    id: 1011,
    title: 'Ford GT',
    image: 'assets/ford-gt-000.png',
    imageAlt: 'Ford GT',
    price: 1100000,
    specifications: {
      modelYear: '2021',
      mileage: '900 miles',
      engine: '3.5L V6 EcoBoost',
      power: '660 HP',
    },
    description: 'Le Mans winner DNA with extreme active aerodynamics.',
    options: [
      { name: 'Carbon Series', price: 75000, selected: false },
      { name: 'Titanium Exhaust', price: 12000, selected: false },
      { name: '6-Point Harness', price: 1500, selected: false },
      { name: 'Heritage Livery', price: 18000, selected: false },
    ],
    addedToFavorites: false,
  },
  {
    id: 1012,
    title: 'Aston Martin Valkyrie',
    image: 'assets/aston-martin-valkyrie-000.png',
    imageAlt: 'Aston Martin Valkyrie',
    price: 3200000,
    specifications: {
      modelYear: '2023',
      mileage: '120 miles',
      engine: '6.5L V12 Hybrid',
      power: '1160 HP',
    },
    description: 'Formula 1 technology adapted for road legality.',
    options: [
      { name: 'AMR Track Pack', price: 150000, selected: false },
      { name: 'Gold Leaf Livery', price: 25000, selected: false },
      { name: 'Custom Seat Fitting', price: 5000, selected: false },
      { name: 'Exposed Carbon', price: 45000, selected: false },
    ],
    addedToFavorites: false,
  },
  {
    id: 1013,
    title: 'Koenigsegg Jesko',
    image: 'assets/koenigsegg-jesko-000.png',
    imageAlt: 'Koenigsegg Jesko',
    price: 3400000,
    specifications: {
      modelYear: '2024',
      mileage: '50 miles',
      engine: '5.0L V8 Twin-Turbo',
      power: '1600 HP',
    },
    description: 'Megacar performance featuring the Light Speed Transmission.',
    options: [
      { name: 'Slingshot Interior', price: 12000, selected: false },
      { name: 'Carbon Wheels', price: 65000, selected: false },
      { name: 'Ghost Package', price: 45000, selected: false },
      { name: 'Hydraulic Autoskin', price: 18000, selected: false },
    ],
    addedToFavorites: false,
  },
  {
    id: 1014,
    title: 'Pagani Huayra Roadster BC',
    image: 'assets/pagani-huayra-roadster-bc-000.png',
    imageAlt: 'Pagani Huayra Roadster BC',
    price: 3700000,
    specifications: {
      modelYear: '2021',
      mileage: '600 miles',
      engine: '6.0L V12 AMG',
      power: '791 HP',
    },
    description: 'A celebration of automotive art and performance material science.',
    options: [
      { name: 'Tempesta Package', price: 180000, selected: false },
      { name: 'Anodized Gold Trim', price: 15000, selected: false },
      { name: 'Custom Luggage Set', price: 22000, selected: false },
      { name: 'Signature Exhaust', price: 12000, selected: false },
    ],
    addedToFavorites: false,
  },
  {
    id: 1015,
    title: 'Lexus LFA',
    image: 'assets/lexus-lfa-000.png',
    imageAlt: 'Lexus LFA',
    price: 850000,
    specifications: {
      modelYear: '2012',
      mileage: '5,000 miles',
      engine: '4.8L V10',
      power: '552 HP',
    },
    description: 'Iconic V10 masterpiece born from Formula 1 racing technology.',
    options: [
      { name: 'Nürburgring Package', price: 75000, selected: false },
      { name: 'Whitest White Paint', price: 5000, selected: false },
      { name: 'Carbon Interior', price: 8000, selected: false },
      { name: 'Red Leather', price: 4000, selected: false },
    ],
    addedToFavorites: false,
  },
  {
    id: 1016,
    title: 'Mercedes-AMG One',
    image: 'assets/mercedes-amg-one-000.png',
    imageAlt: 'Mercedes-AMG One',
    price: 2750000,
    specifications: {
      modelYear: '2023',
      mileage: '200 miles',
      engine: '1.6L V6 Turbo Hybrid',
      power: '1049 HP',
    },
    description: 'Direct Formula 1 powertrain implementation for public roads.',
    options: [
      { name: 'Star Pattern Paint', price: 15000, selected: false },
      { name: 'Race Harness', price: 2500, selected: false },
      { name: 'Protective Film', price: 8000, selected: false },
      { name: 'Custom Helmet', price: 4500, selected: false },
    ],
    addedToFavorites: false,
  },
  {
    id: 1017,
    title: 'Ferrari LaFerrari',
    image: 'assets/ferrari-laferrari-000.png',
    imageAlt: 'Ferrari LaFerrari',
    price: 3200000,
    specifications: {
      modelYear: '2015',
      mileage: '1,800 miles',
      engine: '6.3L V12 Hybrid',
      power: '950 HP',
    },
    description: 'The definitive hybrid hypercar from Maranello.',
    options: [
      { name: 'Carbon Fiber Roof', price: 35000, selected: false },
      { name: 'Telemetry Kit', price: 8000, selected: false },
      { name: 'Track Cameras', price: 6500, selected: false },
      { name: 'Rosso Corsa Paint', price: 12000, selected: false },
    ],
    addedToFavorites: false,
  },
  {
    id: 1018,
    title: 'Porsche 918 Spyder',
    image: 'assets/porsche-918-spyder-000.png',
    imageAlt: 'Porsche 918 Spyder',
    price: 1600000,
    specifications: {
      modelYear: '2015',
      mileage: '3,200 miles',
      engine: '4.6L V8 Hybrid',
      power: '887 HP',
    },
    description: 'Hybrid technology optimized for sheer performance efficiency.',
    options: [
      { name: 'Weissach Package', price: 84000, selected: false },
      { name: 'Liquid Metal Paint', price: 63000, selected: false },
      { name: 'Front Lift System', price: 10500, selected: false },
      { name: 'Carbon Interior', price: 7500, selected: false },
    ],
    addedToFavorites: false,
  },
  {
    id: 1019,
    title: 'McLaren P1',
    image: 'assets/mclaren-p1-000.png',
    imageAlt: 'McLaren P1',
    price: 1800000,
    specifications: {
      modelYear: '2014',
      mileage: '2,500 miles',
      engine: '3.8L V8 Twin-Turbo Hybrid',
      power: '903 HP',
    },
    description: 'A transformative track-to-road hypercar experience.',
    options: [
      { name: 'Exposed Carbon Body', price: 250000, selected: false },
      { name: 'Snorkel Intake', price: 25000, selected: false },
      { name: 'Gold Heat Shield', price: 15000, selected: false },
      { name: 'Meridian Audio', price: 6000, selected: false },
    ],
    addedToFavorites: false,
  },
  {
    id: 1020,
    title: 'Nissan GT-R Nismo',
    image: 'assets/nissan-gt-r-nismo-000.png',
    imageAlt: 'Nissan GT-R Nismo',
    price: 220000,
    specifications: {
      modelYear: '2024',
      mileage: '500 miles',
      engine: '3.8L V6 Twin-Turbo',
      power: '600 HP',
    },
    description: 'The ultimate evolution of the GT-R platform.',
    options: [
      { name: 'Special Edition Paint', price: 5000, selected: false },
      { name: 'Carbon Hood', price: 8000, selected: false },
      { name: 'Titanium Exhaust', price: 4500, selected: false },
      { name: 'Track Pack', price: 12000, selected: false },
    ],
    addedToFavorites: false,
  },
  {
    id: 1021,
    title: 'Lamborghini Huracán STO',
    image: 'assets/lamborghini-huracan-sto-000.png',
    imageAlt: 'Lamborghini Huracán STO',
    price: 340000,
    specifications: {
      modelYear: '2023',
      mileage: '1,500 miles',
      engine: '5.2L V10 NA',
      power: '630 HP',
    },
    description: 'Street-legal race heritage with Super Trofeo aerodynamics.',
    options: [
      { name: 'Contrast Pack', price: 6500, selected: false },
      { name: 'Full Carbon Trim', price: 12000, selected: false },
      { name: 'Lifting System', price: 4000, selected: false },
      { name: 'Magnesium Rims', price: 15000, selected: false },
    ],
    addedToFavorites: false,
  },
  {
    id: 1022,
    title: 'Maserati MC20',
    image: 'assets/maserati-mc20-000.png',
    imageAlt: 'Maserati MC20',
    price: 215000,
    specifications: {
      modelYear: '2024',
      mileage: '800 miles',
      engine: '3.0L V6 Nettuno',
      power: '621 HP',
    },
    description: 'Italian style meets Formula 1 combustion technology.',
    options: [
      { name: 'Carbon Engine Cover', price: 5500, selected: false },
      { name: 'E-LSD', price: 2500, selected: false },
      { name: 'Sonus Faber Audio', price: 4000, selected: false },
      { name: 'Blue Brake Calipers', price: 1200, selected: false },
    ],
    addedToFavorites: false,
  },
  {
    id: 1023,
    title: 'Audi R8 V10 GT RWD',
    image: 'assets/audi-r8-v10-gt-rwd-000.png',
    imageAlt: 'Audi R8 V10 GT RWD',
    price: 250000,
    specifications: {
      modelYear: '2023',
      mileage: '200 miles',
      engine: '5.2L V10 NA',
      power: '602 HP',
    },
    description: 'A limited-edition rear-wheel drive farewell to a legend.',
    options: [
      { name: 'Carbon Ceramic Brakes', price: 9500, selected: false },
      { name: 'Bang & Olufsen Sound', price: 2500, selected: false },
      { name: 'Bucket Seats', price: 4000, selected: false },
      { name: 'Dynamic Steering', price: 1800, selected: false },
    ],
    addedToFavorites: false,
  },
  {
    id: 1024,
    title: 'Dodge Viper ACR',
    image: 'assets/dodge-viper-acr-000.png',
    imageAlt: 'Dodge Viper ACR',
    price: 280000,
    specifications: {
      modelYear: '2017',
      mileage: '3,800 miles',
      engine: '8.4L V10',
      power: '645 HP',
    },
    description: 'Uncompromising raw power and record-setting aerodynamics.',
    options: [
      { name: 'Extreme Aero Package', price: 6500, selected: false },
      { name: 'Carbon Ceramic Matrix', price: 8500, selected: false },
      { name: 'GTS Interior', price: 4500, selected: false },
      { name: 'Brass Monkey Wheels', price: 2000, selected: false },
    ],
    addedToFavorites: false,
  },
  {
    id: 1025,
    title: 'Rimac Nevera',
    image: 'assets/rimac-nevera-000.png',
    imageAlt: 'Rimac Nevera',
    price: 2400000,
    specifications: {
      modelYear: '2024',
      mileage: '150 miles',
      engine: 'Quad Electric Motors',
      power: '1914 HP',
    },
    description: 'Redefining acceleration and speed through quad-motor technology.',
    options: [
      { name: 'Data Logging', price: 5000, selected: false },
      { name: 'Signature Paint', price: 25000, selected: false },
      { name: 'Forged Wheels', price: 12000, selected: false },
      { name: 'Custom Interior', price: 18000, selected: false },
    ],
    addedToFavorites: false,
  },
  {
    id: 1026,
    title: 'Ferrari SF90 Stradale',
    image: 'assets/ferrari-sf90-stradale-000.png',
    imageAlt: 'Ferrari SF90 Stradale',
    price: 550000,
    specifications: {
      modelYear: '2023',
      mileage: '1,100 miles',
      engine: '4.0L V8 PHEV',
      power: '986 HP',
    },
    description: 'Hybrid AWD performance flagship with blistering acceleration.',
    options: [
      { name: 'Assetto Fiorano', price: 55000, selected: false },
      { name: 'Carbon Wheels', price: 28000, selected: false },
      { name: 'Titanium Exhaust', price: 5500, selected: false },
      { name: 'Scuderia Shields', price: 2000, selected: false },
    ],
    addedToFavorites: false,
  },
];
